export default function Head() {
    return (
        <>
            <title>Onchain Events - Oganization and events management</title>
            <meta name="viewport" content="width=device-width, initial-scale=1.0" />
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/img/OnchainEventsLogo.png" />
        </>
    )
}
