export default function Head() {
    return (
        <>
            <title>Mailthereum - Onchain Events</title>
            <meta name="viewport" content="width=device-width, initial-scale=1.0" />
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/images/onchain.jpeg" />
        </>
    )
}
